spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/address_lookup}"  # trufflehog:ignore
    username: "${SPRING_DATASOURCE_USERNAME:postgres}"
    password: "${SPRING_DATASOURCE_PASSWORD:postgres}"
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-local.yaml"
    contexts: local
  docker:
    compose:
      enabled: "${DOCKER_COMPOSE_ENABLED:true}"
